Update testmonitor53019

diff --git a/testmonitor53019 b/testmonitor53019
--- a/testmonitor53019
+++ b/testmonitor53019
@@ -1,22 +1,54 @@
+#!/usr/bin/env bash
+#named as rsyslogtest.sh
+status=$(tail /var/log/messages > grep | date)        # Change the status to test different alert states originally ("0"). 
+currentDate=$(date)
+if [ $status == $currentDate ]; then
+    echo "STATUS:OK - Syslog is up."
+    exit 0;
+   
+ elif [ $status != $currentDate ]; then
+    echo "STATUS:CRITICAL - Syslog could not be reached."
+    exit 2;
+ elif [ $status <= $currentDate ]; then
+    echo "STATUS:WARNING"
+    exit 1;
+else
+   echo "Syslog could not be reached or is not functional."
+   exit 3;
+fi
+#---------------------------PIECES----------------------
 #!/bin/bash
 # This is a script meant to let us test NRPE
 # plugins we write
+#status=$(ps aux | grep -c "")        # Change the status to test different alert states originally ("0"). 
+#if [ $status -lt "100" ]; then
+#    echo "STATUS:OK"
+ #   exit 0;
+ #elif [ $status -ge "150" ]; then
+  #  echo "STATUS:CRITICAL"
+   # exit 2;
+ #elif [ $status -ge "101" ] ; then
+  #  echo "STATUS:WARNING"
+   # exit 1;
+#else
+ #  echo "STATUS:UNKNOWN"
+  # exit 3;
+#fi
 
-status=$(ps aux | grep -c "")        # Change the status to test different alert states originally ("0"). 
-
-if [ $status -lt "100" ]; then
-    echo "STATUS:OK"
-    exit 0;
-    
-  elif [ $status -ge "150" ]; then
-    echo "STATUS:CRITICAL"
-    exit 2;
-    
-  elif [ $status -ge "101" ] ; then
-    echo "STATUS:WARNING"
-    exit 1;
-    
-else
-   echo "STATUS:UNKNOWN"
-   exit 3;
-fi
+#!/bin/bash
+# This is a script meant to let us test NRPE
+# plugins we write
+#status=$(ps aux | grep -c "")        # Change the status to test different alert states originally ("0"). 
+#if [ $status -lt "100" ]; then
+ #   echo "STATUS:OK"
+  #  exit 0;
+  #elif [ $status -ge "150" ]; then
+   # echo "STATUS:CRITICAL"
+   # exit 2;
+  #elif [ $status -ge "101" ] ; then
+   # echo "STATUS:WARNING"
+    #exit 1;
+#else
+ #  echo "STATUS:UNKNOWN"
+  # exit 3;
+#fi
